site_name: 'ELIXIR Norway Documentation'
use_directory_urls: false
repo_name: GitHub
repo_url: 'https://github.com/elixir-no-nels/nels-docs'
repo_uri: blob/main/docs/
site_description: Documentation for ELIXIR Norway and the Norwegian e-Infrastructure for Life Sciences - NeLS
theme: readthedocs
copyright: This documentation under <a href="https://github.com/elixir-no-nels/nels-docs/blob/main/LICENSE">Creative Commons Attribution Share Alike 4.0 International</a> license

markdown_extensions:
  - admonition
  - toc:
        permalink: True  
nav:
 - Home: 'index.md'
 - About: 'about.md'
 - User Documentation: 'user-doc.md'
 - NeLS - SEEK integration: 'integrations.md'
